namespace: h0riz0ns
name: ubuntu_server
version: 0.0.1
license_file: LICENSE
readme: README.md

authors:
  - Fabien Schurter

dependencies:
  ansible.posix: '>=1.6.2,<2.0.0'
  community.general: '>=10.3.0,<11.0.0'
  community.mysql: '>=3.12.0,<4.0.0'
