- name: Sync the hardware clock from the system clock
  listen: time_config_changed
  command: hwclock --systohc

- name: Restart crond
  listen: time_config_changed
  service:
    name: cron
    state: restarted

- name: Register new aliases
  listen: aliases_changed
  command: newaliases

- name: Restart Postfix
  listen: postfix_config_changed
  service:
    name: postfix
    state: reloaded

- name: Reload systemd
  listen: systemd_unit_changed
  command: systemctl daemon-reload

- name: Delete root’s authorized_keys file
  listen: root_login_disabled
  file:
    path: /root/.ssh/authorized_keys
    state: absent

- name: Require a system reboot
  listen: root_login_disabled
  file:
    path: /var/run/reboot-required
    state: touch
    mode: '0644'
