- name: Gather service facts
  service_facts: ~

- name: Set the server’s timezone
  timezone:
    name: '{{ server_timezone }}'
  notify: time_config_changed

- name: Enable NTP sync
  command: timedatectl set-ntp 1
  when: ansible_facts.services['systemd-timesyncd.service'].state|default(omit) != 'running'
  notify: time_config_changed

- name: Generate the required locales
  locale_gen:
    name: '{{ item }}'
    state: present
  with_items: '{{ server_locales }}'
