essential_packages:
  - apt-transport-https
  - bash-completion
  - bzip2
  - ca-certificates
  - curl
  - git
  - gnupg
  - gzip
  - lsb-release
  - mailutils
  - make
  - openssh-client
  - openssh-server
  - python3
  - python3-setuptools
  - python3-virtualenv
  - python3-pip
  - python3-apt
  - software-properties-common
  - tar
  - tree
  - tzdata
  - unattended-upgrades
  - unzip
  - update-notifier-common
  - vim
  - tmux
  - wget

bloat_packages:
  - snapd
  - ufw

root_email_address: root@{{ ansible_fqdn }}
