apt_installed_packages:
  - apt-transport-https
  - bash-completion
  - bzip2
  - ca-certificates
  - curl
  - fake-hwclock
  - git
  - gnupg
  - gzip
  - lsb-release
  - mailutils
  - make
  - openssh-client
  - openssh-server
  - python3
  - python3-setuptools
  - python3-virtualenv
  - python3-pip
  - python3-apt
  - software-properties-common
  - tar
  - tree
  - tzdata
  - unattended-upgrades
  - unzip
  - update-notifier-common
  - util-linux-extra
  - vim
  - tmux
  - wget

apt_removed_packages:
  - snapd
  - ufw

mailing_root_email_address: 'root@{{ ansible_fqdn }}'

users_password_path_template: '{{ password_dir_local_path }}/%s@{{ inventory_hostname }}.pass'

umask_allowed_values:
  - '027'
  - '077'

umask_secure_dir_mode: "{{ '0777'|apply_umask(umask_secure_value) }}"
