[general]

mountpoint = {{ backup_remote_dir }}
backupdir = {{ inventory_hostname }}
format = short
keepdaily = {{ backup_retention_days }}

[source]

from = local
# rsync_options = --verbose --archive --no-recursive --no-group --no-owner --safe-links --dirs --relative --prune-empty-dirs --delete
# rsync_options = --verbose --archive --no-group --no-owner --safe-links --relative --delete

{% for path in backup_paths_included %}
include = {{ path }}
{% endfor %}

{% for path in backup_paths_excluded %}
exclude = {{ path }}
{% endfor %}

[dest]

dest = remote
testconnect = yes
host = {{ backup_remote_host }}
user = {{ backup_remote_user }}
id_file = {{ backup_ssh_key_path }}
