- include_vars:
    file: ../../_globals/vars/main.yml
    name: globals

- import_tasks: _validation.yml

- name: Copy the firewall script
  template:
    src: bin/firewall
    dest: '{{ firewall_script_path }}'
    mode: '0744'
  notify: firewall_config_changed

- name: Copy the firewall service unit
  template:
    src: config/firewall.service
    dest: /etc/systemd/system/firewall.service
    mode: '0644'
  notify: firewall_config_changed

- name: Enable the firewall service
  service:
    name: firewall
    enabled: true
