- name: Register Docker’s official repository
  deb822_repository:
    name: docker
    uris: https://download.docker.com/linux/ubuntu
    architectures: amd64
    suites: '{{ ansible_facts["distribution_release"] }}'
    components: stable
    signed_by: https://download.docker.com/linux/ubuntu/gpg
    state: present
  register: docker_repository

- name: Update the package cache if needed
  apt:
    update_cache: true
  when: docker_repository is changed

- name: Install Docker CE
  apt:
    name:
      - containerd.io
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
    state: latest
    cache_valid_time: '{{ globals.apt_cache_valid_time }}'

- name: Grant some users access to the Docker socket
  user:
    name: '{{ item }}'
    groups: docker
    append: true
  with_items: '{{ docker_users }}'
  notify: docker_users_added
